### PR TITLE
CRAN release v0.11.0

### PR DESCRIPTION
**Pull request by pat-s**
- [x] Resolve all tasks in `cran-comments.md`
- [ ] Run `fledge::release()`
- [ ] When the package is accepted on CRAN, run `fledge::post_release()`

### CODE REVIEW

**Comment by pat-s** [comment]
@christophM 

I've compiled all NEWS and made minor (stylistic) changes to make CRAN happy. Win builder check is pending.

Please do not merge yourself, this release process is semi-automated via {fledge}.
Once all checks are good and I run `fledge::release()`, you'll get an email for the CRAN upload.

LMK if there's anything left you'd like to change/include.

**Comment by pat-s** [comment]
@christophM Win-builder reports

```
Found the following (possibly) invalid DOIs:
  DOI: 10.1214/07-AOAS148
    From: DESCRIPTION
    Status: Internal Server Error
    Message: 500
```

While I think this is a false-positive, we will get an automated rejection when submitting from my experiences. I've tried multiple times but the issue persists.
I think it might be still worth trying and maybe we can argue manually...

**Comment by christophM** [comment]
Thanks a lot! Looking good so far.

The DOI warning seems odd. Because the DOI is valid, and there was no change in the DESCRIPTION since last time.

**Comment by pat-s** [comment]
> The DOI warning seems odd. Because the DOI is valid, and there was no change in the DESCRIPTION since last time.

Yes, but these things happen quite often.

I'll do another run on win-builder, if not, we should still aim for a release and you then just have to argue with a human :)

**Comment by pat-s** [comment]
@christophM Release done, you should have gotten a mail to upload to CRAN.

**Comment by christophM** [comment]
I've received it. Thanks and fingers crossed 🤞

**Comment by christophM** [comment]
I already got an answer from CRAN:

`Please use a serious version number such as 0.11.0 or 0.12.0 for as software release`

I guess we should make it 0.11.0 then? With the new fledge process I am not sure how to proceed. Just update the version and push to this branch?

I also got the the NOTE about the doi, but this wasn't further commented.

**Comment by pat-s** [comment]
It should have been 0.11.0. - sorry, I overlooked this. Not sure how this slipped through.

I've issued another release (and yes, at this stage it's just `fledge::release()`).

**Comment by pat-s** [comment]
@christophM You should have gotten another release mail 6 days ago. Could you give a quick update on what the status is? Appreciated! :)

**Comment by pat-s** [comment]
ping @christophM :)

**Comment by christophM** [comment]
Thanks for the reminder. 

Yes, I got this one:


thanks, package iml_0.11.0.tar.gz is on its way to CRAN.

**Comment by pat-s** [comment]
🎉 Thanks! (I even forgot to look up the presence on CRAN myself, sorry for that!

**Pull request merged**
